#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Jul 03, 2019 12:52:30 AM PDT  platform: Windows NT
import sys
import mysql.connector as sql

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import bankdb_support
def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    bankdb_support.init(root, top)
    root.mainloop()
def create_Toplevel(root, *args, **kwargs):	
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel (w)
    bankdb_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel():
    global w
    w.destroy()
    w = None
class Toplevel1:
    def lop(self):
        try:
            self.conn=sql.MySQLConnection(user="root",password="shrikant2",database="bankdb",charset='utf8')
            print("Connected to Database...")
        except Exception as e:
            print("error::",e)
        ch=0     
        menu="1:Open Account\n2:Depost\n3:Withdraw\n4:Search\n5:Transaction\n6:CloseAccount\n7:List\n8:Interest\n9:Exit"
        self.Listbox1.insert(1,menu)
        self.Listbox1.insert(1,"Enter Choice:")
        ch=self.txtvalue.get("1.0","end-1c")
        
        if ch=='1':
            self.Listbox1.insert(1,"Enter Name:")
            self.Listbox1.insert(1,"Enter Balance:")
            n1=self.txt1.get("1.0","end-1c")
            n2=self.txt1.get("1.0","end-1c")

            an=self.open(n1,n2)
            self.Listbox1.insert(1,"Account Opened : AccNo:",an)
        if ch=='2':
            self.Listbox1.insert(1,"Enter AccNo:")
            an=self.txtvalue.get("1.0","end-1c")
            self.Listbox1.insert(1,"Enter Amount to Deposit:")
            amt=self.txt1.get("1.0","end-1c")
            if(self.deposit(an,amt)):
                self.Listbox1.insert(1,"Amount Deposited..")
            else:
                self.Listbox1.insert(1,"AccNo Not Found..")
        if ch=='3':
            self.Listbox1.insert(1,"Enter AccNo:")
            an=self.txt1.get("1.0","end-1c")
            self.Listbox1.insert(1,"Enter Amount to Withdraw:")
            amt=self.txtvalue.get("1.0","end-1c")
            res=self.withdraw(an,amt)
            if res==-1:
                self.Listbox1.insert(1,"AccNo Not Found..")
            if res==0:
                self.Listbox1.insert(1,"Insufficient Balance")
            else:
                self.Listbox1.insert(1,"Amount Withdrawn Successfully..")
        if ch=='4':
            self.Listbox1.insert(1,"Enter AccNo:")
            an=self.txt1.get("1.0","end-1c")
            row=self.search(an)
            if row==None:
                self.Listbox1.insert(1,"AccNo not Found..")
            else:
                self.Listbox1.insert("Name:",row[1])
                self.Listbox1.insert("Balance:",row[2])
        if ch=='5':
            self.Listbox1.insert(1,"Enter AccNo:")
            an=self.txt1.get("1.0","end-1c")
            row=self.search(an)
            if row==None:
                self.Listbox1.insert(1,"AccNo not Found..")
            else:
                self.Listbox1.insert("Name:",row[1])
                self.Listbox1.insert("Balance:",row[2])
                rows=self.gettrans(an)
                self.Listbox1.insert("-"*37)
                for row in rows:
                    self.Listbox1.insert(1,"|",row[1],"|",row[3],"|",str(row[4]).rjust(8),"|")
                    print("-"*37)
        if ch=='6':
            self.Listbox1.insert("Enter AccNo:")
            an=self.txt1.get()
            row=self.search(an)
            if row==None:
                self.Listbox1.insert(1,"AccNo not Found..")
            else:
                self.Listbox1.insert(1,"Name:",row[1])
                self.Listbox1.insert(1,"Balance:",row[2])
                self.Listbox1.insert(1,"Are you sure ? (y/n):")
                res=self.txt1.get("1.0","end-1c")
            if res=="y":
                close(an)
                self.Listbox1.insert(1,"A/C closed successfully..")
        if ch=='7':
            rows=self.listacc()
            self.Listbox1.insert(1,"-"*42)
            for row in rows:
                self.Listbox1.insert(1,"|",row[0],"|",row[1].ljust(20),"|",str(row[2]).rjust(8),"|")
                self.Listbox1.insert(1,"-"*42)
        if ch=='8':
            self.Listbox1.insert(1,"Enter IRate:")
            r=self.txt1.get("1.0","end-1c")
            self.Listbox1.insert(1,"Enter Period:")
            n=self.txt1.get("1.0","end-1c")
            self.interest(r,n)
            self.Listbox1.insert(1,"Calculated and added..")
        
            
    def open(self,nm,bl):
        smt="insert into accmaster(name,balance) values(%s,%s)"
        cur=self.conn.cursor()
        lst=[nm,bl]
        cur.execute(smt,lst)
        smt="select max(accno) from accmaster"
        cur=self.conn.cursor()
        cur.execute(smt)
        row=cur.fetchone()
        accno=row[0]
        self.trans(accno,'d',bl)
        self.conn.commit()
        return accno
    
    def deposit(self,an,amt):
        smt="update accmaster set balance=balance + %s where accno=%s"
        lst=[amt,an]
        cur=self.conn.cursor()
        cur.execute(smt,lst)
        if cur.rowcount==1:
            self.trans(an,'d',amt)
            self.conn.commit()
            return True
        return False
    
    def withdraw(self,an,amt):
        smt="select balance from accmaster where accno="+an
        cur=self.conn.cursor()
        cur.execute(smt)
        row=cur.fetchone()
        if row==None:
            return -1
        bal=row[0]
        if int(amt)>bal:
            return 0
        smt="update accmaster set balance=balance - %s where accno=%s"
        cur=self.conn.cursor()
        params=[amt,an]
        cur.execute(smt,params)
        self.trans(an,'w',amt)
        self.conn.commit()
        return 1
    
    def search(self,an):
        smt="select * from accmaster where accno="+an
        cur=self.conn.cursor()
        cur.execute(smt)
        row=cur.fetchone()
        return row
    
    def gettrans(self,an):
        smt="select * from trans where accno="+an
        cur=self.conn.cursor()
        cur.execute(smt)
        rows=cur.fetchall()
        return rows

    def close(self,an):
        smt="delete from accmaster where accno="+an
        cur=self.conn.cursor()
        cur.execute(smt)
        smt="delete from trans where accno="+an
        cur=self.conn.cursor()
        cur.execute(smt)
        self.conn.commit()

    def listacc(self):
        smt="select * from accmaster"
        cur=self.conn.cursor()
        cur.execute(smt)
        rows=cur.fetchall()
        return rows

    def interest(self,r,n):
        rows=self.listacc()
        for row in rows:
            an=row[0]
            bal=row[2]
            si=bal*float(r)*float(n)/100
            self.deposit(an,si)
    
    def trans(self,an,ty,amt):
        smt="insert into trans(accno,transtype,amount) values(%s,%s,%s)"
        lst=[an,ty,amt]
        cur=self.conn.cursor()
        cur.execute(smt,lst)   
                              
        
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Courier New} -size 10"
        font9 = "-family {Segoe UI} -size 9"

        top.geometry("982x762+522+150")
        top.title("bank db")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.143, rely=0.026, relheight=0.833
                , relwidth=0.667)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#a2d8d6")
        self.Frame1.configure(highlightbackground="#52d84e")
        self.Frame1.configure(highlightcolor="#000000")
        self.Frame1.configure(width=755)

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.212, rely=0.014, relheight=0.65
                   , relwidth=0.442)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font=font10)
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(highlightbackground="#d9d9d9")
        self.Listbox1.configure(highlightcolor="black")
        self.Listbox1.configure(selectbackground="#c4c4c4")
        self.Listbox1.configure(selectforeground="black")
        self.Listbox1.configure(width=334)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.199, rely=0.691, height=41, width=134)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#6ca2d8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Enter your choice here :''')

        self.txtvalue = tk.Text(self.Frame1)
        self.txtvalue.place(relx=0.397, rely=0.691, relheight=0.063
                  , relwidth=0.27)
        self.txtvalue.configure(background="white")
        self.txtvalue.configure(font=font9)
        self.txtvalue.configure(foreground="black")
        self.txtvalue.configure(highlightbackground="#d9d9d9")
        self.txtvalue.configure(highlightcolor="black")
        self.txtvalue.configure(insertbackground="black")
        self.txtvalue.configure(selectbackground="#c4c4c4")
        self.txtvalue.configure(selectforeground="black")
        self.txtvalue.configure(width=204)
        self.txtvalue.configure(wrap='word')


        self.txt1 = tk.Text(self.Frame1)
        self.txt1.place(relx=0.397, rely=0.777, relheight=0.092
                , relwidth=0.27)
        self.txt1.configure(background="white")
        self.txt1.configure(font=font9)
        self.txt1.configure(foreground="black")
        self.txt1.configure(highlightbackground="#d9d9d9")
        self.txt1.configure(highlightcolor="black")
        self.txt1.configure(insertbackground="black")
        self.txt1.configure(selectbackground="#c4c4c4")
        self.txt1.configure(selectforeground="black")
        self.txt1.configure(width=204)
        self.txt1.configure(wrap='word')


        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.464, rely=0.892, height=34, width=97)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d8272d")
        self.Button1.configure(disabledforeground="#a34b7d")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''choice''')
        self.Button1.configure(width=97)
        self.Button1.configure(command=self.lop)
        self.menubar = tk.Menu(top, font=('Segoe UI', 9, ), bg=_bgcolor
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)
if __name__ == '__main__':
    vp_start_gui()
    
    
    

   
    
    

   








