#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Jul 03, 2019 12:52:05 AM PDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 982x762+522+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "bank db"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#a2d8d6} -height 635 \
        -highlightbackground {#52d84e} -highlightcolor {#000000} -width 655 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel" 1
    set site_3_0 $top.fra43
    listbox $site_3_0.lis45 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -height 452 -highlightbackground {#d9d9d9} -highlightcolor black \
        -selectbackground {#c4c4c4} -selectforeground black -width 334 
    .top42.fra43.lis45 configure -font font10
    .top42.fra43.lis45 insert end text
    vTcl:DefineAlias "$site_3_0.lis45" "Listbox1" vTcl:WidgetProc "Toplevel" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#6ca2d8} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} \
        -text {Enter your choice here :} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1" vTcl:WidgetProc "Toplevel" 1
    text $site_3_0.tex47 \
        -background white -font {-family {Segoe UI} -size 9} \
        -foreground black -height 44 -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 204 \
        -wrap word 
    .top42.fra43.tex47 configure -font font9
    .top42.fra43.tex47 insert end text
    vTcl:DefineAlias "$site_3_0.tex47" "txtvalue" vTcl:WidgetProc "Toplevel" 1
    button $site_3_0.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d8272d} -disabledforeground {#a34b7d} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} -pady 0 \
        -text choice 
    vTcl:DefineAlias "$site_3_0.but43" "Button1" vTcl:WidgetProc "Toplevel" 1
    place $site_3_0.lis45 \
        -in $site_3_0 -x 160 -y 30 -width 334 -relwidth 0 -height 452 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 150 -y 500 -width 134 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex47 \
        -in $site_3_0 -x 300 -y 500 -width 204 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 350 -y 560 -width 97 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font {-family {Segoe UI} -size 9} \
        -foreground {#000000} -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 140 -y 20 -width 655 -relwidth 0 -height 635 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

